spring:
  profiles:
    include: config_mysql, config_mvc

intro-service:
  base-url: http://intro-service:8081

mq-publish:
  base-url: http://mq-publish:8082

mq-consume:
  base-url: http://mq-consume:8083

cache-service:
  base-url: http://cache-service:8084