###
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2021
###

security:
  enable: false

spring:
  profiles:
    include: config_h2, config_mvc
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,
      com.oembedler.moon.graphql.boot.GraphQLWebAutoConfiguration
