server:
port: ${PORT:8080}
servlet:
  session:
    timeout: 1h

## SPRING
spring:
  main:
    banner-mode: "off"

  session:
    timeout: 1h

  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

  messages:
    basename: i18n/messages
    #spring.mvc.locale=en #To make it work massages.properties file should be left, and messages_en.properties created
    ##spring.messages.cache-seconds=-1
    encoding: UTF-8

  datasource:
    url: jdbc:mysql://mysql/makeitfinemysqldocker
    username: makeitfineuser
    password: makeitfinepass
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1

  # Show or not log for each sql query
  jpa:
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: validate
      # Naming strategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
        # stripped before adding them to the entity manager)
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    enabled: false
    url: jdbc:mysql://mysql/makeitfinemysqldocker
    user: makeitfineuser
    password: makeitfinepass
    locations: classpath:db/migration/mysql

