###
#
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2020
#
###

spring:
  profiles:
    include: config_mysql, config_mvc

intro-service:
  base-url: http://localhost:8081

mq-publish:
  base-url: http://localhost:8082

mq-consume:
  base-url: http://localhost:8083

cache-service:
  base-url: http://localhost:8084
