spring:
  profiles:
    include: config_mysql, config_mvc

intro-service:
  base-url: http://localhost:8081

mq-publish:
  base-url: http://localhost:8082

mq-consume:
  base-url: http://localhost:8083