## SPRING
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

  messages:
    basename: i18n/messages
    #spring.mvc.locale=en #To make it work massages.properties file should be left, and messages_en.properties created
    ##spring.messages.cache-seconds=-1
    encoding: UTF-8

  #=============================
  # Data Source Config
  #=============================
  jpa:
    hibernate:
      ddl-auto: validate

  # Web url: /h2-console (the default jdbc url is `jdbc:h2:mem:testdb`)
  h2:
    console:
      enabled: true

flyway:
  locations: classpath:db/migration/h2