language: java
jdk:
  - openjdk11

before_install:
  - sudo apt-get install jq
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.0/codacy-coverage-reporter-6.0.0-assembly.jar

script:
  mvn clean verify

cache:
  directories:
    - $HOME/.m2

after_success:
  - java -jar codacy-coverage-reporter-6.0.0-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml

notifications:
  slack:
    rooms:
      secure: bbRlLE0Jflh/wHLXZNqNR4DBg0W1uFG6kvlgeDdM2AP1NbVzi3TYvL6NYKglMNgteyN2W2YuDt1lStSuEcbOhyzsgH30nY2ykzHzz8DwDi/6LG07vUmZH+CVg3tfk7PRaX+2Bf6oErWCip5qf5PfstCLSCy50V5GjX98YK654N9BcLnfj+JUnlih9NwmAdnFGYtL8sW65VMmRuxDpbDjIxeaP+yaf+JSQ6ioGcO0/H6p+RhtOpaSHmqYCVOwUtVV6DbJcniKecyimn0actxPUMZ7ueIP9PCtC3JMv5ApIBuF8nO6NIRWSpdJ5cgDmBUDh209kLHsV5Hp/b+mC1I3a3j5PdtYzVVfoYfemTYnkjyje0A8vw4sZa5WGx8C9Y7vph6UFnB1+JJJMBnzzK1diFfwc0GRtjVRoB3p0m5ubkFZw4unTW9CvngPl/SIoMjkMLknxO1GXGS/Iv/e3tWI0wtNHw4UpgblC966Nw77+r0OtoRek1zuIIzW4MLPu+gSOUScrNao5fsrWNQagPttNlhZCLOA68CnaTSAAoo5Wd63ab1luC+yAGqlb0n40kvaoLX15QnanESeHSsXVcrYfnuYHYJXOZh5G/OcWCuvr1M/4djCw0Qybiq0ezsiUhbwCTnSBoC994QB42+LUHx2WxaU48lxSXFRRsoF2t8SNSU=
    on_success: change
    on_failure: always
