version: '2.1'

services:

  mysql:
    image: mysql
    container_name: mys
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: drupal3
    networks:
      mifnet_back:
        ipv4_address: 172.16.238.2
    ports:
      - 3311:3306

  java8_maven:
    depends_on:
      - mysql
#    image: maven:3.5-ibmjava-alpine
    image: stingion/practice:j8m_repos # docker with saved .m2/repositories
    container_name: j8m
    environment:
      docker_env: "true"
      indebug: "false"
    networks:
      mifnet_back:
        ipv4_address: 172.16.238.3
    ports:
      - 8085:8080
      - 5010:5005
    volumes:
      - .:/data/original
#    working_dir: /data/makeitfine
    command: # 3 lines (before 'cd mainside' can be deleted for fast dev)
      - /bin/sh
      - -c
      - |
          cd /data
          echo 'tail -f /data/log.txt' >> output.sh
          cp -R /data/original /data/makeitfine
          cd makeitfine
          mvn clean  > /data/log.txt
          mvn process-resources flyway:clean flyway:migrate -pl mainside >> /data/log.txt
          sleep 300s
    stdin_open: true
    tty: true
    ## Usefull commands:docke
    # tail -f /data/log.txt
    # watch -n 1 netstat -lpn
    #
    #entrypoint: /bin/sh -c

networks:
  mifnet_back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
