version: '3.7'

services:

  mainside:
    ports:
      - 5005:5005
    command:
      - /bin/sh
      - -c
      - |
        ./waiting.sh
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar -Dspring.profiles.active=docker /app.war

  intro-service:
    ports:
      - 5006:5006
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -jar -Dspring.profiles.active=docker /app.war

  mq-publish:
    ports:
      - 5007:5007
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -jar -Dspring.profiles.active=docker /app.war

  mq-consume:
    ports:
      - 5008:5008
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008 -jar -Dspring.profiles.active=docker /app.war

  cache-service:
    ports:
      - 5009:5009
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009 -jar -Dspring.profiles.active=docker /app.war
