## Info for docker-compose console commands:
# start: dcu; status: dcp; stop: dcdw;
version: '3.7'

services:

  mysql:
    image: mysql:5.7.22
    container_name: mif_mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: rootpassdocker
      MYSQL_DATABASE: makeitfinemysqldocker
      MYSQL_USER: makeitfineuser
      MYSQL_PASSWORD: makeitfinepass
    ports:
      - 3311:3306

  flyway:
    depends_on:
      - mysql
    image: flyway/flyway
    container_name: mif_flyway
    command: -url=jdbc:mysql://mysql/makeitfinemysqldocker -user=makeitfineuser -password=makeitfinepass -connectRetries=60 migrate
    volumes:
      - ./mainside/src/main/resources/db/migration/mysql:/flyway/sql

  mainside:
    depends_on:
      - flyway
    image: koresmosto/mainside
    container_name: mif_mainside
    ports:
      - 8085:8080
