version: '3.7'

services:

  mysql:
    image: mysql:5.7.22
    container_name: mys
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassdocker
      MYSQL_DATABASE: makeitfinemysqldocker
      MYSQL_USER: makeitfineuser
      MYSQL_PASSWORD: makeitfinepass
    networks:
      mifnet_back:
        aliases:
          - mysql_server
    ports:
      - 3311:3306

  java8_maven:
    depends_on:
      - mysql
    image: stingion/practice:j8m_repos # docker with '.m2/repositories' saved
    container_name: j8m
    environment:
      docker_env: "true"
      indebug: "true"
    networks:
      mifnet_back:
        aliases:
          - app_server
    ports:
      - 8085:8080
      - 5010:5005
    volumes:
      - .:/data/original
    command: # 3 lines before 'cd mainside' can be 'changed to mvn clean verify' for fast dev
      - /bin/sh
      - -c
      - |pp
          cd /data
          echo 'tail -f /data/log.txt' >> output.sh
          cp -R /data/original /data/makeitfine
          cd makeitfine
          mvn clean  > /data/log.txt
          mvn process-resources flyway:clean flyway:migrate -pl mainside >> /data/log.txt
          mvn clean verify >> /data/log.txt
          cd mainside
          mvn spring-boot:run >> /data/log.txt
    stdin_open: true
    tty: true

networks:
  mifnet_back:
    driver: "bridge"
