version: '2.1'

services:

  mysql:
    image: mysql
    container_name: mys
    environment:
      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_USER: "makeitfinemysql"
#      MYSQL_PASSWORD: "makeitfine121"
#      MYSQL_DATABASE: "makeitfinemysql"
#      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      mifnet_back:
        ipv4_address: 172.16.238.2

  java8_maven:
    depends_on:
      - mysql
    image: maven:3.5-ibmjava-alpine
    container_name: j8m
    environment:
      docker_env: "true"
      nodebug: "false"
    networks:
      mifnet_back:
        ipv4_address: 172.16.238.3
    volumes:
      - .:/data/original
    working_dir: /data/original
    command: /bin/sh -c "mvn clean  > /data/log.txt"
    working_dir: /data/original/mainside
    command: /bin/sh -c "mvn process-resources flyway:clean flyway:migrate > /data/log.txt"
    working_dir: /data/original
    command: /bin/sh -c "mvn verify  > /data/log.txt"
    working_dir: /data/original/mainside
    command: /bin/sh -c "mvn spring-boot:run  > /data/log.txt"
    stdin_open: true
    tty: true
    ## Usefull commands:docke
    # tail -f /data/log.txt
    # watch -n 1 netstat -lpn
    #
    #entrypoint: /bin/sh -c

volumes:
  mysql_data:

networks:
  mifnet_back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
