version: '3.7'

services:

  mysql:
    image: mysql:5.7.22
    container_name: mif_mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: rootpassdocker
      MYSQL_DATABASE: makeitfinemysqldocker
      MYSQL_USER: makeitfineuser
      MYSQL_PASSWORD: makeitfinepass
    ports:
      - 3311:3306

  flyway:
    depends_on:
      - mysql
    image: flyway/flyway
    container_name: mif_flyway
    command: -url=jdbc:mysql://mysql/makeitfinemysqldocker -user=makeitfineuser -password=makeitfinepass -connectRetries=60 migrate
    volumes:
      - ./mainside/src/main/resources/db/migration/mysql:/flyway/sql

  java11_maven:
    depends_on:
      - flyway
    image: adoptopenjdk/maven-openjdk11
    container_name: mif_mainside
    environment:
      docker_env: "true"
      #Debug mode isn't working for Java 11 (issue planed to be fixed)
      indebug: "false"
    ports:
      - 8085:8080
      - 5010:5005
    volumes:
      - .:/data/original
      - type: volume
        source: mifrepo_m2
        target: /root/.m2/repository
        #Todo: Remove sleep 5s from command changed by something else
    command: # 3 lines before 'cd mainside' can be 'changed to mvn clean verify' for fast dev
      - /bin/sh
      - -c
      - |
        cd /data
        echo 'tail -f /data/log.txt' >> output.sh
        cp -R /data/original /data/makeitfine
        cd makeitfine
        mvn clean  > /data/log.txt
        echo "Necessary empirical/experimental sleep 5s (for mvn repos init && mysql connection)" >> /data/log.txt
        sleep 5s
        mvn clean verify >> /data/log.txt
        cd mainside
        mvn spring-boot:run >> /data/log.txt
    stdin_open: true
    tty: true

volumes:
  mifrepo_m2:
