## Todo: Info for docker-compose console commands:
# todo: start: dcu; status: dcp; stop: dcdw;
# todo: Build for docker: mci -Pdocker

#todo: Build locally: $> wd && mcv && c mainside/ && m spring-boot:run
#todo: Build locally debug: $> wd && mcv && c mainside/ && m spring-boot:run -Pdebug
#todo: Build docker: $> wd && mci -Pdocker && dcu

#todo: Info for Elastic Stack:
#todo:Info: elastic, filebeat, logstash folders should be writeable (chmod 777 -R ..)
#todo:Info: filebeat.docker.yml >>> https://github.com/primait/docker-filebeat/issues/13 >>>
# (sudo chown root filebeat/filebeat.docker.yml)
# (sudo chmod 600 filebeat/filebeat.docker.yml)

#todo: run $>./run/elastic/elastic.sh to up Elastic Stack
version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ESV}
    container_name: mif_elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elasticstack/elasticsearch/data:/usr/share/elasticsearch/data:rw # Persistence data

  logstash:
    image: docker.elastic.co/logstash/logstash:${ESV}
    container_name: mif_logstash
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./elasticstack/logstash/pipeline:/usr/share/logstash/pipeline:ro # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:${ESV}
    container_name: mif_kibana
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ESV}
    container_name: mif_filebeat
    volumes:
      - ./elasticstack/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./elasticstack/filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash

  mysql:
    image: mysql:5.7.22
    container_name: mif_mysql
    restart: on-failure
    ports:
      - 3311:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassdocker
      MYSQL_DATABASE: makeitfinemysqldocker
      MYSQL_USER: makeitfineuser
      MYSQL_PASSWORD: makeitfinepass

  flyway:
    depends_on:
      - mysql
    image: flyway/flyway:6.1.3
    container_name: mif_flyway
    command: -url=jdbc:mysql://mysql/makeitfinemysqldocker -user=makeitfineuser -password=makeitfinepass -connectRetries=60 migrate
    volumes:
      - ./mainside/src/main/resources/db/migration/mysql:/flyway/sql

  mongo:
    image: mongo:4.2.2
    container_name: mif_mongo
    restart: always
    ports:
      - 27117:27017
    volumes:
      - ./intro-service/src/main/resources/db/migration/mongo/init/:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: ${mongo_root_user}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_root_pass}

  mongo-express:
    image: mongo-express:0.49.0
    container_name: mif_mongo-express
    restart: always
    ports:
      - 8101:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${mongo_root_user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${mongo_root_pass}

  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: mif_rabbitmq
    restart: always
    ports:
      - 5772:5672
      - 15772:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${rabbitmq_user}
      RABBITMQ_DEFAULT_PASS: ${rabbitmq_pass}

  redis:
    image: bitnami/redis:5.0.7
    container_name: mif_redis
    restart: always
    ports:
      - 6479:6379
    environment:
      REDIS_PASSWORD: ${redis_pass}
    command: /run.sh --maxmemory 256mb

  mainside:
    depends_on:
      - flyway
    image: koresmosto/mainside
    container_name: mif_mainside
    ports:
      - 8085:8080
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  intro-service:
    depends_on:
      - mongo
    image: koresmosto/intro-service
    container_name: mif_intro-service
    ports:
      - 8086:8081
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  mq-publish:
    depends_on:
      - rabbitmq
    image: koresmosto/mq-publish
    container_name: mif_mq-publish
    ports:
      - 8087:8082
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  mq-consume:
    depends_on:
      - rabbitmq
    image: koresmosto/mq-consume
    container_name: mif_mq-consume
    ports:
      - 8088:8083
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  cache-service:
    depends_on:
      - redis
    image: koresmosto/cache-service
    container_name: mif_cache-service
    ports:
      - 8089:8084
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"