###
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2020
###

spring:
  cache:
    type: redis
  redis:
    host: @redis.host@
    port: @redis.port@
    password: @redis.password@
