###
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2021
###

spring:
  data:
    mongodb:
      authentication-database: @mongodb.authentication-database@
      username: @mongodb.username@
      password: @mongodb.password@
      database: @mongodb.database@
      port: @mongodb.port@
      host: @mongodb.host@
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
