spring:
  data:
    mongodb:
      authentication-database: @mongodb.authentication-database@
      username: @mongodb.username@
      password: @mongodb.password@
      database: @mongodb.database@
      port: @mongodb.port@
      host: @mongodb.host@