# todo: should be removed in future/ info to wiki
# start mongo db:
# $> sudo /usr/bin/mongod --auth --port 27017 --dbpath /var/lib/mongodb
# login mongo db (admin):
# $> mongo --port 27017  --authenticationDatabase "admin" -u "admin" -p
# login mongo db (introuser):
# $> mongo --port 27017  --authenticationDatabase "admin" -u "introuser" -p

#Local MongoDB config
spring:
  data:
    mongodb:
      authentication-database: @mongodb.authentication-database@
      username: @mongodb.username@
      password: @mongodb.password@
      database: @mongodb.database@
      port: @mongodb.port@
      host: @mongodb.host@

mongoMigration:
  isEnabled: @mongodb.migration.active@
  allPrivilegesUser: @mongodb.migration.allPrivilegesUser@
  allPrivilegesPass: @mongodb.migration.allPrivilegesPass@
