###
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2020
###

spring:
  rabbitmq:
    host: @rabbitmq.host@
    port: @rabbitmq.port@
    username: @rabbitmq.username@
    password: @rabbitmq.password@
rabbitmq:
  queue: @rabbitmq.queue@
