###
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2020
###

spring:
  #=============================
  # Data Source Config
  #=============================
  datasource:
    url: jdbc:mysql://localhost:3506/db
    username: sa
    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
